job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-india
    APP_HOSTPATH: india
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-india
    NEWRELIC_APPNAME: P4 India Development
    WP_DB_NAME: planet4-india_wordpress_develop
    WP_STATELESS_BUCKET: planet4-india-stateless-develop
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: release.k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: india
    HELM_RELEASE: planet4-india-release
    NEWRELIC_APPNAME: P4 India Release
    WP_DB_NAME: planet4-india_wordpress_release
    WP_STATELESS_BUCKET: planet4-india-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: www.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: india
    HELM_RELEASE: planet4-india-master
    MIN_REPLICA_COUNT: 2
    NEWRELIC_APPNAME: P4 India Production
    WP_DB_NAME: planet4-india_wordpress_master
    WP_STATELESS_BUCKET: planet4-india-stateless
